### ISSUE TITLE
Patch does not work on Magento 2.2.4

### ISSUE THREAD

**Issue by skynixukraine** [Space48/magento2-patches#11]
https://monosnap.com/file/uhyW8avPOHWKzKBtvvXgQpHSc8ueIx

**Comment by punkstar** [comment]
It's odd that this package would cause that kind of error. This extension provides a patch file that's applied by [vaimo/composer-patches](https://github.com/vaimo/composer-patches) after a package is installed. If there was a problem applying the patch then it would say so and, if there was a runtime error introduced by the patch, I'd only expect that to be shown when you try and run Magento.

Something else that's strange is that I don't see "Issue #13929: Images can't be uploaded using WYSIWYG if media directory is a symlink" (the patch description in your screenshot) anywhere in this repo.

* Can you please provide your `composer.json` file?
* Does installing Magento succeed without the `space48/magento2-patches` package present?

**Comment by diazwatson** [comment]
@skynixukraine I am closing this issue now, if the problem still exists, please feel free to reopen and comment
